import { useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowUpRight, Check, ChevronDown, Download, ExternalLink, Github, Linkedin, Mail, Menu, MapPin, Phone, Send, X } from 'lucide-react'
import { profile, projects, skillGroups, softSkills } from './data/portfolio'

const reveal = { hidden: { opacity: 0, y: 22 }, show: { opacity: 1, y: 0, transition: { duration: 0.55 } } }
const resumePath = '/Boopathi-G-Resume.pdf'

function SectionHeading({ eyebrow, title, children }) {
  return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{children}</div>
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [sent, setSent] = useState(false)
  const navItems = ['About', 'Skills', 'Projects', 'Experience', 'Education', 'Achievements', 'Contact']
  const handleSubmit = (event) => { event.preventDefault(); setSent(true); window.location.href = `mailto:${profile.email}?subject=Portfolio enquiry from ${event.currentTarget.name.value}&body=${encodeURIComponent(event.currentTarget.message.value)}` }

  return <div>
    <header className="site-header"><div className="nav-shell"><a href="#home" className="brand" onClick={() => setMenuOpen(false)}><span className="brand-mark">BG</span><span>{profile.name}</span></a><button className="menu-button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button><nav className={menuOpen ? 'nav-links open' : 'nav-links'}>{navItems.map((item) => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setMenuOpen(false)}>{item}</a>)}<a className="nav-resume" href={resumePath} download><Download size={16} /> Resume</a></nav></div></header>

    <main>
      <section className="hero section-wrap" id="home"><div className="hero-copy"><motion.div initial="hidden" animate="show" variants={reveal}><p className="eyebrow">HELLO, I'M</p><h1>{profile.name}<span>.</span></h1><p className="hero-title">{profile.title}</p><p className="hero-intro">Final-year Artificial Intelligence and Data Science student passionate about Full Stack Development and UI/UX, with a strong foundation in software development, programming, and problem-solving.</p><div className="hero-actions"><a className="button button-primary" href="#projects">View my projects <ArrowUpRight size={17} /></a><a className="button button-secondary" href={resumePath} download><Download size={17} /> Download resume</a></div><div className="social-row"><a href={profile.github} target="_blank" rel="noreferrer"><Github size={17} /> GitHub</a><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={17} /> LinkedIn</a><a href={`mailto:${profile.email}`}><Mail size={17} /> Email</a></div></motion.div></div><motion.div className="hero-aside" initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .8, delay: .15 }}><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="profile-stamp"><span>AI & DATA SCIENCE</span><strong>Building with<br />clarity & purpose.</strong><small>{profile.location}</small></div></motion.div></section>

      <section className="band" id="about"><div className="section-wrap about-grid"><SectionHeading eyebrow="01 / ABOUT" title="Curious by nature. Focused by craft." /><div className="about-content"><p className="lead">I am a final-year AI & Data Science student interested in the space where thoughtful interfaces meet reliable software.</p><p>I enjoy building efficient, user-friendly applications, working through complex problems with an analytical mindset, and continuously learning new technologies. I am comfortable collaborating with others and turning ideas into clear, useful digital experiences.</p><div className="objective"><span>CAREER OBJECTIVE</span><p>To begin my career as a Full Stack Developer where I can apply my skills in web development, programming, and UI/UX to build efficient and user-friendly applications while continuously learning and growing as a software professional.</p></div></div></div></section>

      <section className="section-wrap" id="skills"><SectionHeading eyebrow="02 / CAPABILITIES" title="A practical toolkit." /><div className="skills-grid">{skillGroups.map((group, index) => <motion.div className="skill-group" key={group.label} initial="hidden" whileInView="show" viewport={{ once: true, amount: .2 }} variants={reveal}><span className="skill-number">0{index + 1}</span><h3>{group.label}</h3><div className="skill-list">{group.items.map((item) => <span key={item}>{item}</span>)}</div></motion.div>)}</div><div className="soft-row"><span className="eyebrow">SOFT SKILLS</span>{softSkills.map((item) => <span className="soft-skill" key={item}><Check size={15} /> {item}</span>)}</div></section>

      <section className="band projects-band" id="projects"><div className="section-wrap"><SectionHeading eyebrow="03 / SELECTED WORK" title="Things I have built." ><p>Projects shaped by curiosity, practical problem-solving, and a desire to make technology easier to use.</p></SectionHeading><div className="projects-grid">{projects.map((project) => <motion.article className="project-card" key={project.name} initial="hidden" whileInView="show" viewport={{ once: true, amount: .15 }} variants={reveal}><div className="project-top"><span>{project.number}</span><span>{project.type}</span></div><h3>{project.name}</h3><p>{project.description}</p>{project.features.length > 0 && <ul>{project.features.map((feature) => <li key={feature}><Check size={15} />{feature}</li>)}</ul>}<div className="project-footer"><span>Project work</span></div></motion.article>)}</div></div></section>

      <section className="section-wrap" id="experience"><SectionHeading eyebrow="04 / EXPERIENCE" title="Learning through doing." /><div className="timeline"><article className="timeline-item"><span className="timeline-dot" /><div><span className="timeline-label">INTERNSHIP</span><h3>Web Development Intern</h3><p className="timeline-company">Algoxoan Pvt. Ltd., Salem</p><ul><li>Assisted in front-end development using HTML, CSS, and JavaScript</li><li>Fixed UI bugs and improved website responsiveness</li><li>Collaborated with senior developers to implement new features</li></ul></div></article><article className="timeline-item"><span className="timeline-dot" /><div><span className="timeline-label">INTERNSHIP</span><h3>Data Science Intern</h3><ul><li>Practical exposure to data analysis and machine learning concepts</li><li>Worked with Python, real-world datasets, and data preprocessing</li><li>Practiced data visualization and strengthened analytical thinking</li></ul></div></article></div></section>

      <section className="band" id="education"><div className="section-wrap"><SectionHeading eyebrow="05 / EDUCATION" title="The foundation." /><div className="education-grid"><article className="education-card featured"><span>2023 — 2027</span><h3>B.Tech — Artificial Intelligence and Data Science</h3><p>Annapoorana Engineering College, Salem, Tamil Nadu</p><strong>CGPA: 8.20 <small>(as of Semester 6)</small></strong></article><article className="education-card"><span>2021 — 2023</span><h3>Higher Secondary — 12th</h3><p>GOV Higher Secondary School, Salem</p><strong>Percentage: 68%</strong></article></div></div></section>

      <section className="section-wrap" id="achievements"><SectionHeading eyebrow="06 / MILESTONES" title="A few proud moments." /><div className="achievement-grid">{['Participated in National Level Hackathon — 2024', 'Completed 100+ coding problems on HackerRank', 'Secured 2nd place in Inter-College Coding Competition — 2023'].map((item, index) => <div className="achievement" key={item}><span>0{index + 1}</span><p>{item}</p><ArrowUpRight size={18} /></div>)}</div></section>

      <section className="resume-cta band" id="resume"><div className="section-wrap resume-inner"><div><span className="eyebrow">08 / RESUME</span><h2>Want to know more about my journey?</h2><p>Explore my education, skills, projects, internships, and achievements in detail.</p></div><a className="button button-primary" href={resumePath} download><Download size={17} /> Download resume</a></div></section>

      <section className="contact-section" id="contact"><div className="section-wrap contact-grid"><div><SectionHeading eyebrow="07 / CONTACT" title="Let's connect." /><p className="contact-intro">Have an opportunity, idea, or question? I would be glad to hear from you.</p><div className="contact-details"><a href={`mailto:${profile.email}`}><Mail size={18} /><span>{profile.email}</span></a><a href={`tel:${profile.phone.replaceAll(' ', '')}`}><Phone size={18} /><span>{profile.phone}</span></a><span><MapPin size={18} />{profile.location}</span></div><div className="contact-social"><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={19} /></a><a href={profile.github} target="_blank" rel="noreferrer"><Github size={19} /></a><a href={`mailto:${profile.email}`}><Mail size={19} /></a></div></div><form className="contact-form" onSubmit={handleSubmit}><label htmlFor="name">Name<input id="name" name="name" required placeholder="Your name" /></label><label htmlFor="email">Email<input id="email" name="email" type="email" required placeholder="you@example.com" /></label><label htmlFor="message">Message<textarea id="message" name="message" required rows="4" placeholder="Tell me a little about your message..." /></label><button className="button button-primary" type="submit">{sent ? 'Opening email client' : 'Send message'} <Send size={16} /></button><small>This form opens your email client and does not send data to a server.</small></form></div></section>
    </main>

    <footer><div className="section-wrap footer-inner"><span className="brand"><span className="brand-mark">BG</span> {profile.name}</span><span>© 2026 · Built with intention.</span><a href="#home">Back to top <ChevronDown size={15} className="rotate" /></a></div></footer>
  </div>
}

export default App
